### ISSUE TITLE
How to setup? How to use? and many more questions...

### ISSUE THREAD

**Issue by anoduck** [yousefvand/secret-service#17]
Recommended trying this repo by a developer, and understandably he was attempting his best to find a resolution, but did not install it himself. 

So, it built without a hitch, and I was successful at configuring it to run from `~/.local/bin` without systemd using dinit, using a 32 character password. 

So... I still have no clue what the user configuration file is for at `~/.secret-service.yaml`. It was not created automatically on running the script, and there is no explanation of what is supposed to be located within it or even what it's function is for. So, it's purpose is quite mysterious.

Although the script runs, and does appear to use the freedesktop socket of dbus. This seems to be the extent of it's function. Since, there is no other information on it's functionality.

When attempting to probe the service using keyring, I received the following error.

```bash

Gkr-Message: 05:33:07.983: response from daemon contained a bad collection path: /org/freedesktop/secrets/aliases/default
Gkr-Message: 05:33:07.983: call to daemon returned an invalid response: (null).(null)()

```

which can't be good.

**Comment by yousefvand** [comment]
the `yaml` file is for service configuration. If you want your password file at `/etc/systemd/user` you need to give permission to your user to read it.
The last two errors are dbus errors, look at https://github.com/yousefvand/secret-service/tree/main/docs

**Comment by anoduck** [comment]
> the `yaml` file is for service configuration. If you want your password file at `/etc/systemd/user` you need to give permission to your user to read it. The last two errors are dbus errors, look at https://github.com/yousefvand/secret-service/tree/main/docs

This will take some pondering, and a review. My system is OpenBSD, which neither has systemd or a linux variant of dbus. It has messagebus.

**Comment by yousefvand** [comment]
for systemd you can run `secretserviced` file manually but for dbus I have no idea because API is based on dbus.

**Comment by anoduck** [comment]
@yousefvand I am getting it figured out now. I can just add `secretserviced` to my `~/.config/i3/config`  file and have it run on login. I also learned DBUS and messagebus are basically the same thing, dbus actually launches a service called messagebus in linux computers. 

~~Looks like I will have to work around a `du` issue, this happens fairly often when running OpenBSD. Commands like `grep`, `stat`, and `du` are not the gnu variant, but you can install the gnu variant and alias them.~~ Well, nevermind. 

She is built, working on the configuration.

**Comment by anoduck** [comment]
OK, well she is up and running. Everything looks good. The tests are checking out just fine. So everything is good on your end. I just need to get with the developer of nheko and work out why his app is not picking up on it.
