### ISSUE TITLE
gpg-agent integration?

### ISSUE THREAD

**Issue by gardar** [yousefvand/secret-service#20]
First of all thanks for creating this project, it's great to finally see someone doing a minimal secret service implementation.

Have you looked into integration with gpg-agent? 
- To create a secretservice gpg-agent socket, something like the ssh agent that comes with gpg-agent ( take a look at `gpg-agent-browser.socket`, `gpg-agent-ssh.socket`, etc. ) I'd love to see `gpg-agent-secretservice.socket`:smile:
- Or to to simply encrypt/decrypt the masterpassword for the systemd service and store in the agent.

**Comment by yousefvand** [comment]
hey
no I didn't see gpg-agent spec. Actually I'm not gonna make big changes to this project it is 11k loc already and take a lot of time from me to make changes. Maybe on a vacation. anyway thanks for the suggestion.
