### ISSUE TITLE
Ideas on how to move ~/.secret-service directory elsewhere?

### ISSUE THREAD

**Issue by Frontear** [yousefvand/secret-service#21]
I'd prefer not to have it clutter my home directory, I kinda already have a lot of things there, .gnupg .ssh .pki .cargo etc etc etc its getting quite messy. Been cleaning it up and this is a slight setback. Are there documented ways, or intended ways to move this directory, perhaps with an environment variable of some type like `SECRET_SERVICE_HOME` or the like?

**Comment by yousefvand** [comment]
No I hard coded home directory into application. In early phases of design I was thinking of placing it at `$HOME/.config` but it is more than config (database, logs...). I will consider your need in next revision.
