### ISSUE TITLE
VSCode keyring no longer accepts this in the latest update

### ISSUE THREAD

**Issue by Frontear** [yousefvand/secret-service#22]
Now this is most likely a VSCode issue but raising it here as it may be possible to fix. Running VSCode results in this popup:

![image](https://github.com/yousefvand/secret-service/assets/31909298/251cb940-0fca-47b8-8fff-d2445276f3c5)

Now bear in mind literally every single `org.freedesktop.secrets` running on a non-DE environment (like i3, Sway, Hyprland, etc) seems to be having this issue, at least whats that mentioned throughout the tracking thread on VSCode's issue on GitHub https://github.com/microsoft/vscode/issues/187338.

**Comment by yousefvand** [comment]
I have implemented API exactly from draft, this  issues should root from somewhere else.

**Comment by lvdh** [comment]
FWIW, the latest release of this service works flawlessly, on my setup at least: Linux + open source build of VSCode.

- distro:
    - EndeavourOS/Arch Linux
    - kernel 6.1.49-1-lts
- desktop:
    - window manager: i3
    - desktop environment: none
- packages:
    - [aur/secret-service](https://aur.archlinux.org/packages/secret-service) 0.2.2-1
    - [extra/code](https://archlinux.org/packages/extra/x86_64/code/) 1.81.1-1
        - built by Arch Linux, from [microsoft/vscode](https://github.com/microsoft/vscode)
    - [aur/1password](https://aur.archlinux.org/packages/1password) 8.10.13-5
- configuration:
    - Followed the secret-service README after package install.
    - 1Password picked it up as a valid `org.freedesktop.secrets` backend once `secretserviced` was running.

Awesome backend choice for 1Password, by the way. Thank you!
