### ISSUE TITLE
FIXME: Are they the same?

### ISSUE THREAD

**Issue by scrouthtv** [yousefvand/secret-service#8]
Greetings,

after using secret-service for a day now, I've got these messages in my log:
```
Jul 11 10:02:15 archlinux secretserviced[887]: time="Sun, 11 Jul 2021 10:02:15 +0200" level=debug 
msg="FIXME: Are they the same?" <some secrets>
Jul 11 10:02:15 archlinux secretserviced[887]: time="Sun, 11 Jul 2021 10:02:15 +0200" level=trace
msg="GetSecrets result: map <some secrets>
```

And they are the same. Maybe that helps with anything.

**Comment by yousefvand** [comment]
Thanks for the information, it is very helpful.
I should apologize for extensive logging (default hast set to `TRACE`). I'll remove this log in next releases. My estimate is one year for this project to get to `v1.0.0`  and I so appreciate your PR.

**Comment by scrouthtv** [comment]
No worries :)
